FROM ubuntu:18.04

# This is the base php environment for both testing and production.

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update

RUN apt-get install -y git
RUN apt-get install -y zip unzip

RUN apt-get install -y php
RUN apt-get install -y php-curl
RUN apt-get install -y php-bcmath
RUN apt-get install -y php-memcache
RUN apt-get install -y php-memcached
RUN apt-get install -y php-mbstring
RUN apt-get install -y libapache2-mod-php
RUN apt-get install -y php-xml
RUN apt-get install -y php-mysql
RUN apt-get install -y php-gd
RUN apt-get install -y php-zip

# Setup python 3 options
RUN apt-get install -y python3.6
RUN apt-get install -y python3.7
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2
RUN update-alternatives --config python3
RUN update-alternatives  --set python3 /usr/bin/python3.6



# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
#RUN php -r "if (hash_file('sha384', 'composer-setup.php') === 'baf1608c33254d00611ac1705c1d9958c817a1a33bce370c0595974b342601bd80b92a3f46067da89e3b06bff421f182') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer
#RUN php -r "unlink('composer-setup.php');"